### ISSUE TITLE
generated docs are getting wrong version number

### ISSUE THREAD

**Issue by toloudis** [bioio-devs/bioio#58]
### Describe the Bug

generated docs are getting wrong version number

### Expected Behavior

generated docs are getting right version number

### Reproduction

https://bioio-devs.github.io/bioio/OVERVIEW.html

**Comment by BrianWhitneyAI** [comment]
@evamaxfield do you know what is going on here?

**Comment by evamaxfield** [comment]
I believe I do but I'll take a look later today!

**Comment by BrianWhitneyAI** [comment]
amazing thank you! My thoughts are that during the docs build the distribution isnt built/accessible so `bioio.__version__` which uses `version(bioio)` cannot read the version and just makes a low level dev version. not sure how to fix though...

**Comment by evamaxfield** [comment]
Seems like docs still have incorrect version. I will make a new PR to keep testing things out and I will make the docs job run on pushes to the branch so that I can iteratively test. Ultimately though, seems like we may just want to change this job to only run on tag releases so a little bit of both understanding what is going on and fixing it seems likely.

**Comment by toloudis** [comment]
Bump! Sometimes we want to link to the docs for very new users and it looks bad if the version number is still some early dev prerelease build.

**Comment by evamaxfield** [comment]
ugh. sorry. i continue to just be busy. i think the fix for this is to move the docs to build on each release rather than build on push to main.
